name: nghinv_device_info
description: A plugin for get device info. Support Android, iOS, Linux, MacOS, Windows, Web.
version: 0.0.1
homepage: https://github.com/nghinv-software/flutter-nghinv-device-info
maintainer: nghinv (@Nghi-NV)

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nghinv.device_info
        pluginClass: NDeviceInfoPlugin
      ios:
        pluginClass: NDeviceInfoPlugin
      linux:
        pluginClass: NDeviceInfoPlugin
      macos:
        pluginClass: NDeviceInfoPlugin
      windows:
        pluginClass: NDeviceInfoPluginCApi
      web:
        pluginClass: NDeviceInfoWeb
        fileName: nghinv_device_info_web.dart
